# TODO: make this composite a standalone action
name: Attack container CI
inputs:
  docker_tag:
    description: "docker tag to attack"
    required: true
  snyk_token:
    description: snyk token
    requried: true
  pat:
    description: "personal access token for zap"
    required: true
  github_token:
    description: "github token"
    required: true
runs:
  using: composite
  steps:
    #
    # wapiti
    # emits .wapiti/generated_report/report.html
    # for now, base default scan
    - name: Wapiti Scan
      uses: gipo355/vuln-docker-scanners-wapiti-action@v1.0.3
      with:
        target: "http://localhost:8080/tomcat-webapp-boilerplate/app"
        github_token: ${{ inputs.github_token }}
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@d2a07475d467566c9a3e3c700f31f47724aa1060 # v0.10.0
      with:
        token: ${{ inputs.pat }}
        # docker_name: ${{ env.TEST_TAG }}
        target: "http://localhost:8080/tomcat-webapp-boilerplate/app"
        # rules_file_name: ".zap/rules.tsv"
        cmd_options: "-a"
    # TODO: ZAP emits json or creates an issue only
    # possibly create an action
    # /usr/bin/touch report_json.json report_md.md report_html.html
    # /usr/bin/chmod a+w report_json.json report_md.md report_html.html
    # TODO: post-processing: create custom action to convert zap json to sarif
    # check trivy, snyk actions for reference on parsing
    #
    # run custom container with nmap
    # TODO: add  self actions: finish nmap
    # WARN: can't use docker action with scanners
    # docker actions don't pass the --network=host  flag
    # must create node action to run docker container
    # check zap action for reference
    # https://github.com/zaproxy/action-full-scan
    #
    # NOTE: nmap deactivated for now as it possibly exposes github vulns
    #
    # - name: Nmap Scan
    #   uses: gipo355/vuln-docker-scanners-nmap-action@debeebb1184d79dd8e7f1148aebe58a8b2f86efe # v1.1.4
    #   with:
    #     github_token: ${{ inputs.github_token }}
    #     target: "localhost"
    #     vulner: true
    #     vulscan: true
    #     port: "8080"
    #     flags: "-sV"
    #     generate_reports: true
    #
    # init scanning for vulnerabilities
    - name: Set up Snyk CLI to check for security issues
      uses: snyk/actions/setup@d406fd286b663eb8c6f8adcced4f7bcd199c0a3f
    - name: login to snyk
      shell: bash
      run: snyk auth ${{ inputs.snyk_token }}
      # FIXME: sarif output doesn't work
      # TODO: post-processing the snyk report to remove nulls
      #
      # Error: Code Scanning could not process the submitted SARIF file:
      # could not convert rules: invalid security severity value, is not a number: null
      # ConfigurationError: Code Scanning could not process the submitted SARIF file:
      # could not convert rules: invalid security severity value, is not a number: null
      #     at run (/home/runner/work/_actions/github/codeql-action/f079b8493333aace61c81488f8bd40919487bd9f/lib/upload-sarif-action.js:70:15)
      #     at async runWrapper (/home/runner/work/_actions/github/codeql-action/f079b8493333aace61c81488f8bd40919487bd9f/lib/upload-sarif-action.js:84:9)
      #
      #   # Snyk can be used to break the build when it detects vulnerabilities.
      #   # In this case we want to upload the issues to GitHub Code Scanning
    - name: run snyk container
      shell: bash
      run: snyk container test ${{ inputs.docker_tag }} --file=Dockerfile --sarif > snyk-container.sarif || true
      # - name: display json output
      #   shell: bash
      #   run: cat snyk-container.sarif
      # - name: Upload snyk container result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@f079b8493333aace61c81488f8bd40919487bd9f # v3
      #   with:
      #     sarif_file: snyk-container.sarif # :FIXME: <-- this is broken, post-process
      # - name: Upload vulner report to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@f079b8493333aace61c81488f8bd40919487bd9f # v3
      #   with:
      #     sarif_file: nmap-reports/vulner/vulner-report.sarif
#
# TODO: add load test, wapiti, and other scanners
#
# TODO: how to scan? on PR? on release?
#
# pen test and put comment in pr with the results now using PR image
# we will replicate the pen test with cron on another action on the dev branch tag released image
