name: Download and submit dependency graph on PR workflow
on:
  workflow_run:
    workflows: ["Dependency Submission on PR Workflow"]
    types: [completed]
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  submit-dependency-graph:
    name: Submit Dependency Graph job
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Download and submit dependency graph on PR step
        uses: gradle/actions/dependency-submission@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
        with:
          dependency-graph: download-and-submit
