name: Dependency Submission On Push Workflow
on:
  push:
    branches: ["dev"]
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  dependency-submission:
    name: Dependency Submission On Push Job
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: ./.github/actions/ci-setup
        name: Setup CI environment
      - name: Generate and submit dependency graph Step
        uses: gradle/actions/dependency-submission@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
