name: Download and submit dependency graph on PR workflow
on:
  workflow_run:
    workflows: ["Dependency Submission on PR Workflow"]
    types: [completed]
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  submit-dependency-graph:
    name: Submit Dependency Graph job
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Download and submit dependency graph on PR step
        uses: gradle/actions/dependency-submission@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
        with:
          dependency-graph: download-and-submit
